function modal(title, body, onSubmit, submitText='Lưu'){
  const dlg=$('#modal'), mb=$('#modalBody'); mb.innerHTML=`<div class="modal-head"><h3>${title}</h3><button class="mini-btn" type="button" onclick="document.getElementById('modal').close()">✕</button></div><div class="modal-content">${body}</div><div class="modal-actions"><button class="btn" type="button" onclick="document.getElementById('modal').close()">Hủy</button><button class="btn primary" type="submit">${submitText}</button></div>`;
  const form=$('#modalForm'); form.onsubmit=async e=>{e.preventDefault(); const fd=Object.fromEntries(new FormData(form).entries()); try{form.querySelector('[type=submit]').disabled=true; await onSubmit(fd); dlg.close(); await refresh(); toast('Đã lưu');}catch(err){toast(err.message,true)}finally{form.querySelector('[type=submit]')&&(form.querySelector('[type=submit]').disabled=false)}}; dlg.showModal();
}
function options(items,value,label=x=>x.name){return items.map(x=>`<option value="${x.id}" ${x.id===value?'selected':''}>${esc(label(x))}</option>`).join('')}

function openTransaction(id=''){
  const t=state.transactions.find(x=>x.id===id)||{}; const type=t.transaction_type||'expense';
  modal(id?'Sửa giao dịch':'Thêm giao dịch',`<div class="form-grid"><div class="field"><label>Loại</label><select name="transaction_type" id="txType"><option value="expense" ${type==='expense'?'selected':''}>Chi tiêu</option><option value="income" ${type==='income'?'selected':''}>Thu nhập</option><option value="transfer" ${type==='transfer'?'selected':''}>Chuyển khoản</option></select></div><div class="field"><label>Số tiền</label><input name="amount" type="number" min="1" step="1" value="${esc(t.amount||'')}" required></div><div class="field"><label>Ngày</label><input name="transaction_date" type="date" value="${esc(t.transaction_date||today())}" required></div><div class="field"><label>Tiền tệ</label><select name="currency"><option value="JPY" ${(t.currency||state.base)==='JPY'?'selected':''}>JPY</option><option value="VND" ${(t.currency||state.base)==='VND'?'selected':''}>VND</option></select></div><div class="field" id="categoryField"><label>Danh mục</label><select name="category_id" id="txCategory"></select></div><div class="field"><label>Tài khoản</label><select name="account_id"><option value="">— Không chọn —</option>${options(activeAccounts(),t.account_id)}</select></div><div class="field hidden" id="transferField"><label>Chuyển đến</label><select name="transfer_account_id"><option value="">— Chọn tài khoản —</option>${options(activeAccounts(),t.transfer_account_id)}</select></div><div class="field full"><label>Ghi chú</label><input name="note" value="${esc(t.note||'')}" placeholder="Tùy chọn"></div></div>`,async fd=>{await api('save_transaction',{...fd,id:id||null,fx_rate:1,category_id:fd.category_id||null,account_id:fd.account_id||null,transfer_account_id:fd.transfer_account_id||null})});
  const typeEl=$('#txType'), cat=$('#txCategory'); const sync=()=>{const tr=typeEl.value==='transfer'; $('#categoryField').classList.toggle('hidden',tr); $('#transferField').classList.toggle('hidden',!tr); if(!tr){const cats=activeCategories(typeEl.value);cat.innerHTML='<option value="">— Chọn danh mục —</option>'+options(cats,t.category_id)}}; typeEl.onchange=sync; sync();
}
async function deleteTransaction(id){if(!confirm('Xóa giao dịch này?'))return;try{await api('delete_transaction',{id});await refresh();toast('Đã xóa giao dịch')}catch(e){toast(e.message,true)}}

function versionForCategory(id){ const vs=state.categoryVersions.filter(v=>v.category_id===id&&String(v.effective_month).slice(0,7)<=state.month).sort((a,b)=>String(b.effective_month).localeCompare(String(a.effective_month))); return vs[0]; }
function openCategory(id=''){
  const c=state.categories.find(x=>x.id===id)||{}; const v=id?versionForCategory(id):null; const dir=c.direction||'expense'; const ct=(v?.cost_type||c.cost_type||'variable'); const amount=v?.planned_amount??c.planned_amount??0;
  modal(id?'Sửa danh mục':'Thêm danh mục',`<div class="form-grid"><div class="field"><label>Tên</label><input name="name" value="${esc(v?.name||c.name||'')}" required></div><div class="field"><label>Nhóm</label><select name="direction" id="catDirection"><option value="expense" ${dir==='expense'?'selected':''}>Chi tiêu</option><option value="income" ${dir==='income'?'selected':''}>Thu nhập</option></select></div><div class="field" id="costField"><label>Tính chất</label><select name="cost_type"><option value="fixed" ${ct==='fixed'?'selected':''}>Cố định</option><option value="variable" ${ct==='variable'?'selected':''}>Biến động</option></select></div><div class="field" id="planField"><label>Số tiền kế hoạch</label><input name="planned_amount" type="number" min="0" step="1" value="${esc(amount)}"></div><div class="field"><label>Áp dụng từ tháng</label><input name="effective_month" type="month" value="${state.month}" required><small>Tháng trước không bị thay đổi.</small></div><div class="field"><label>Màu</label><input name="color" type="color" value="${esc(c.color||'#64748b')}"></div></div>`,async fd=>{await api('save_category',{...fd,id:id||null,effective_month:`${fd.effective_month}-01`,planned_amount:fd.direction==='income'?0:fd.planned_amount,cost_type:fd.direction==='income'?null:fd.cost_type})});
  const d=$('#catDirection'); const sync=()=>{$('#costField').classList.toggle('hidden',d.value==='income');$('#planField').classList.toggle('hidden',d.value==='income')};d.onchange=sync;sync();
}
async function archiveCategory(id){if(!confirm('Ẩn danh mục này? Giao dịch cũ vẫn được giữ.'))return;try{await api('archive_category',{id});await refresh();toast('Đã ẩn danh mục')}catch(e){toast(e.message,true)}}

function openAccount(id=''){
  const a=state.accounts.find(x=>x.id===id)||{}; modal(id?'Sửa tài khoản':'Thêm tài khoản',`<div class="form-grid"><div class="field full"><label>Tên tài khoản</label><input name="name" value="${esc(a.name||'')}" required></div><div class="field"><label>Loại</label><select name="account_type">${[['cash','Tiền mặt'],['bank','Ngân hàng'],['credit','Thẻ tín dụng'],['savings','Tiết kiệm'],['investment','Đầu tư'],['loan_receivable','Phải thu'],['loan_payable','Phải trả']].map(([v,l])=>`<option value="${v}" ${(a.account_type||'cash')===v?'selected':''}>${l}</option>`).join('')}</select></div><div class="field"><label>Tiền tệ</label><select name="currency"><option value="JPY" ${(a.currency||state.base)==='JPY'?'selected':''}>JPY</option><option value="VND" ${(a.currency||state.base)==='VND'?'selected':''}>VND</option></select></div><div class="field full"><label>Số dư ban đầu</label><input name="opening_balance" type="number" step="1" value="${esc(a.opening_balance||0)}"></div></div>`,fd=>api('save_account',{...fd,id:id||null}));
}
async function archiveAccount(id){if(!confirm('Ẩn tài khoản này? Giao dịch cũ vẫn được giữ.'))return;try{await api('archive_account',{id});await refresh();toast('Đã ẩn tài khoản')}catch(e){toast(e.message,true)}}

function openGoal(id=''){
  const g=state.goals.find(x=>x.id===id)||{}; modal(id?'Sửa mục tiêu':'Thêm mục tiêu',`<div class="form-grid"><div class="field full"><label>Tên mục tiêu</label><input name="name" value="${esc(g.name||'')}" required></div><div class="field"><label>Mục tiêu</label><input name="target_amount" type="number" min="1" value="${esc(g.target_amount||'')}" required></div><div class="field"><label>Đã có</label><input name="current_amount" type="number" min="0" value="${esc(g.current_amount||0)}"></div><div class="field"><label>Tiền tệ</label><select name="currency"><option value="JPY" ${(g.currency||state.base)==='JPY'?'selected':''}>JPY</option><option value="VND" ${(g.currency||state.base)==='VND'?'selected':''}>VND</option></select></div><div class="field"><label>Ngày mục tiêu</label><input name="target_date" type="date" value="${esc(g.target_date||'')}"></div></div>`,fd=>api('save_goal',{...fd,id:id||null,is_completed:n(fd.current_amount)>=n(fd.target_amount)}));
}
async function deleteGoal(id){if(!confirm('Xóa mục tiêu này?'))return;try{await api('delete_goal',{id});await refresh();toast('Đã xóa mục tiêu')}catch(e){toast(e.message,true)}}
function openLoan(id=''){
  const l=state.loans.find(x=>x.id===id)||{}; modal(id?'Sửa khoản vay/nợ':'Thêm khoản vay/nợ',`<div class="form-grid"><div class="field full"><label>Người / đơn vị</label><input name="counterparty" value="${esc(l.counterparty||'')}" required></div><div class="field"><label>Loại</label><select name="loan_type"><option value="borrowed" ${(l.loan_type||'borrowed')==='borrowed'?'selected':''}>Đi vay · mình phải trả</option><option value="lent" ${l.loan_type==='lent'?'selected':''}>Cho vay · mình phải thu</option></select></div><div class="field"><label>Tiền tệ</label><select name="currency"><option value="JPY" ${(l.currency||state.base)==='JPY'?'selected':''}>JPY</option><option value="VND" ${(l.currency||state.base)==='VND'?'selected':''}>VND</option></select></div><div class="field"><label>Số tiền gốc</label><input name="principal" type="number" min="1" value="${esc(l.principal||'')}" required></div><div class="field"><label>Còn lại</label><input name="remaining_amount" type="number" min="0" value="${esc(l.remaining_amount??l.principal??'')}"></div><div class="field"><label>Ngày bắt đầu</label><input name="start_date" type="date" value="${esc(l.start_date||today())}"></div><div class="field"><label>Hạn trả</label><input name="due_date" type="date" value="${esc(l.due_date||'')}"></div><div class="field full"><label>Ghi chú</label><input name="note" value="${esc(l.note||'')}"></div></div>`,fd=>api('save_loan',{...fd,id:id||null}));
}
async function deleteLoan(id){if(!confirm('Xóa khoản vay/nợ này?'))return;try{await api('delete_loan',{id});await refresh();toast('Đã xóa khoản nợ')}catch(e){toast(e.message,true)}}

async function saveHousehold(e){e.preventDefault(); const fd=Object.fromEntries(new FormData(e.currentTarget).entries()); try{await api('save_household',fd);await refresh();toast('Đã lưu cài đặt')}catch(err){toast(err.message,true)}}
async function exportData(){try{const d=await api('export');const blob=new Blob([JSON.stringify(d,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`taichinh-gd-${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('Đã tạo bản sao')}catch(e){toast(e.message,true)}}
async function copyPrivateLink(){const url=`${location.origin}${location.pathname}#k=${encodeURIComponent(state.key)}`;try{await navigator.clipboard.writeText(url);toast('Đã sao chép link riêng')}catch{prompt('Sao chép link này:',url)}}
function forgetDevice(){if(!confirm('Xóa khóa khỏi thiết bị này? Bạn cần link riêng để mở lại.'))return;localStorage.removeItem(KEY_STORE);location.reload()}

$('#unlockForm').addEventListener('submit', async e=>{e.preventDefault(); const k=$('#unlockKey').value.trim(); if(k.length<32){toast('Khóa không hợp lệ',true);return} localStorage.setItem(KEY_STORE,k); location.reload();});
$('#nav').addEventListener('click',e=>{const b=e.target.closest('button[data-view]');if(b)navigate(b.dataset.view)});
$('#mobileNav').addEventListener('click',e=>{const b=e.target.closest('button[data-view]');if(b)navigate(b.dataset.view)});
$('#quickAdd').addEventListener('click',()=>openTransaction());
$('#monthPicker').addEventListener('change',async e=>{try{setLoading(true);await loadMonth(e.target.value);toast(`Đã chuyển sang ${e.target.value.replace('-','/')}`)}catch(err){toast(err.message,true)}finally{setLoading(false)}});
window.state=state; Object.assign(window,{navigate,render,openTransaction,deleteTransaction,openCategory,archiveCategory,openAccount,archiveAccount,openGoal,deleteGoal,openLoan,deleteLoan,exportData,copyPrivateLink,forgetDevice});
boot();